name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  coverage:
    strategy: # allows pinning additional nightly
      fail-fast: false # allows continue past failure of one toolchain if multiple
      matrix:
        toolchain: [ nightly ]

    # 360 mins is gh actions default
    timeout-minutes: ${{ matrix.toolchain == 'nightly' && 10 || 360 }}

    name: Coverage
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: llvm-tools-preview

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Collect coverage
        run: |
          cargo llvm-cov --no-report nextest
          cargo llvm-cov --no-report --doc
          cargo llvm-cov report --doctests --lcov --output-path lcov.info

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: false
