name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: stable
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: nightly
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Test nightly feature (if possible)
        if: ${{ matrix.toolchain == 'nightly' }}
        run: |
          cargo test --target ${{ matrix.target }} --features=nightly
          cargo test --target ${{ matrix.target }} --benches --features=nightly
      - name: Test default features
        run: |
          cargo test --target ${{ matrix.target }}